version: '3'
services:
  ############################
  # RabbitMQ
  ############################
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      retries: 10    
      start_period: 20s
  ############################
  # PublisherAPI + Dapr sidecar
  ############################
  publisherapi:
    build: ./PublisherAPI
    ports:
      - "50002:50001"
      - "8081:80"
      - "3601:3500"
    depends_on:
      - placement
#    networks:
#      - hello-dapr
  publisherapi-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "publisherapi",
    "-app-port", "80",
    "-placement-host-address", "placement:50006",
#    "-dapr-http-port", "3601",
#    "-dapr-grpc-port", "50002",
    "-resources-path", "./components"]
    volumes:
        - "./components/:/components"
    depends_on:
      rabbitmq:
        condition: service_healthy
      publisherapi:
        condition: service_started
      #- publisherapi
      #- rabbitmq
    network_mode: "service:publisherapi"  
  ############################
  # InvokeAPI + Dapr sidecar
  ############################
  invokeapi:
    build: ./InvokeAPI
    ports:
      - "8080:80"
      - "3602:3500"
    depends_on:
      - placement
#    networks:
#      - hello-dapr
  invokeapi-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "invokeapi",
    "-app-port", "80",
#    "-dapr-http-port", "3602",
    "-placement-host-address", "placement:50006"]
    depends_on:
      - invokeapi
    network_mode: "service:invokeapi"
  ############################
  # SubscriberAPI + Dapr sidecar
  ############################
  subscriberapi:
    build: ./SubscriberAPI
    ports:
      - "8082:80"
      - "3603:3500"
    depends_on:
      - placement
  subscriberapi-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
    "-app-id", "subscriberapi",
    "-app-port", "80",
#    "-dapr-http-port", "3602",
    "-placement-host-address", "placement:50006",
    "-resources-path", "./components"]
    volumes:
        - "./components/:/components"
    depends_on:
      rabbitmq:
        condition: service_healthy
      subscriberapi:
        condition: service_started
    network_mode: "service:subscriberapi"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
#    networks:
#      - hello-dapr
#networks:
#    hello-dapr: