# For "Orders"

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order-subscription
spec:
  topic: newOrders
  route: /order
  pubsubname: order-queue
scopes:
  - subscriberapi

---
# Test

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: test-subscription
spec:
  topic: test
  route: /test
  pubsubname: order-queue
scopes:
  - subscriberapi